$(function(){

	var headHtml = '<div class="navbar-header">'
            +'<div class="navbar-brand">'
            +' <a href="#" class="logo">'
            +'<img src="images/xr_logo.png" alt="">'
            + '</a>'
            +'</div>'
            +'<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">'
              +'<span class="icon-bar"></span>'
              +'<span class="icon-bar"></span>'
              +'<span class="icon-bar"></span>'
            +'</button>'
          +'</div>'
          +'<div class="collapse navbar-collapse hidden-xs" id="bs-example-navbar-collapse-1">'
            +'<ul class="nav navbar-nav hidden-xs">'
              +'<li><a href="index.html">首页</a>'
                                +'<span></span>'
                            +'</li>'
              +'<li>'
                +'<a href="#">产品</a>'
                
                +'<div class="nav_tow">'
                  +'<dl class="hidden-xs hidden-sm">'
                    +'<dt>官网建设 </dt>'
                    +'<dd><a href="pages/marketing.html" target="_blank">营销型云商宝<i></i></a></dd>'
                    +'<!-- <dd><a href="#">营销型手机官网<i></i></a></dd> -->'
                    +'<dd class="hidden"><a href="#">全网通讯系统</a></dd>'
                    +'<!-- <dd><a href="#">微商宝</a></dd> -->'
                    +'<!-- <dd><a href="#">微分销<i></i></a></dd> -->'
                  +'</dl>'
                                    +'<p></p>'
                  +'<dl>'
                    +'<dt>营销推广 </dt>'
                    +'<dd><a href="flow.html" target="_blank">流量宝</a></dd>'
                    +'<dd><a href="zhiT.html" target="_blank">直通车</a></dd>'
                    +'<dd class="hidden-xs hidden-sm"><a href="http://db.wayboo.com/" target="_blank">生意帮</a></dd>'
                    +'<dd><a href="B2B.html" target="_blank">B2B广告联盟</a></dd>'
                  +'</dl>'
                                    +'<p></p>'
                  +'<dl class="hidden-xs hidden-sm">'
                    +'<dt>品牌推广 </dt>'
                    +'<dd><a href="pages/cctv.html" target="_blank">CCTV品牌推广<i></i></a></dd>'
                    +'<dd><a href="pages/aaapinpai.html" target="_blank">AAA信用等级认证</a></dd>'
                  +'</dl>'
                                    +'<p></p>'
                  +'<dl class="hidden-xs hidden-sm">'
                    +'<dt>增值服务 </dt>'
                    +'<dd><a href="pages/TrademarkRegistration.html" target="_blank">商标注册</a></dd>'
                    +'<dd><a href="pages/certification.html" target="_blank">高新技术企业认证<i></i></a></dd>'
                    +'<dd><a href="pages/accounts.html" target="_blank">代理记账</a></dd>'
                  +'</dl>'
                +'</div>'
             +' </li>'
              +'<li class="hidden-sm hidden-md"><a href="http://db.wayboo.com/" target="_blank">大数据分析</a></li>'
              +'<li class="hidden-sm hidden-md"><a href="http://mb.wayboo.net.cn/" target="_blank">模板展示</a></li>'
              +'<li class="hidden-sm hidden-md"><a href="#add_about">关于我们</a></li>'
              +'<li><a href="http://syb.wayboo.com/" target="_blank">生意帮&nbsp;&nbsp;Login'
                +'<img src="images/syb_03.png" alt="">'
              +'</a></li>'
            +'</ul>'
         +' </div>';

         var nav = $('nav .container');
         nav.html(headHtml);

         var footerHtml = '<div class="left_f">'
                  +' <a href="/index.html" class="hidden-sm hidden-xs"><img src="images/footer_logo.png" alt=""></a>'
                  +' <a href="/index.html" class="hidden-md hidden-lg"><img src="images/add_index_footer_03.png" alt=""></a>'
                  +' <span></span>'
                  +' <p>数字营销整合</p>'
                  +' <p class="second">外包服务平台</p>'
                   +'<ul class="hidden-xs">'
                       +'<li><a href="index.html">首页</a></li>'
                      +' <li>|</li>'
                       +'<li><a href="#">产品</a></li>'
                       +'<li>|</li>'
                       +'<li><a href="http://db.wayboo.com/" target="_blank">大数据分析</a></li>'
                       +'<li>|</li>'
                       +'<li><a href="http://mb.wayboo.net.cn/" target="_blank">模板展示</a></li>'
                       +'<li>|</li>'
                       +'<li><a href="#add_about">关于我们</a></li>'
                   +'</ul>'
               +'</div>'
                 +'<div class="middle_f">'
                     +'<img src="images/erweima.png" alt="" class="hidden-xs hidden-sm">'
                    +'<img src="images/add_index_footer_07.png" alt="" class="hidden-md hidden-lg">'
                +'</div>'
                +'<div class="right_f">'
                    +'<p>全国统一服务热线 : 40000-99990</p>'
                    +'<p>E-mail : fang@wayboo.cn</p>'
                    +'<p>add : 北京市朝阳区保利东方中心A座17层</p>'
                    +'<p>web : www.wayboo.com</p>'
                    +'<p>Copyright 2013-2018 www.wayboo.com All Rights Reserved.'
                        +'信融科技 版权所有 京IPC备 13035649号-2</p>'
                +'</div>';
         var footer = $('.footer .container');
         footer.html(footerHtml);
})